apiVersion: v1
kind: ConfigMap
metadata:
  name: contoso-test-config
  namespace: namespace-workflow-1746497961928
  labels:
    app.kubernetes.io/name: contoso-test
    kubernetes.azure.com/generator: devhub
data: