apiVersion: v1
kind: ConfigMap
metadata:
  name: contoso-test-2-config
  namespace: namespace-workflow-1746498186908
  labels:
    app.kubernetes.io/name: contoso-test-2
    kubernetes.azure.com/generator: devhub
data: