apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: contoso
  labels:
    app.kubernetes.io/name: contoso
    app.kubernetes.io/part-of: contoso-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: contoso