apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: contosoair
  labels:
    app.kubernetes.io/name: contosoair
    app.kubernetes.io/part-of: contosoair-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: contosoair