apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: contosotest
  labels:
    app.kubernetes.io/name: contosotest
    app.kubernetes.io/part-of: contosotest-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: contosotest