apiVersion: v1
kind: Service
metadata:
  name: contoso-test-2
  namespace: namespace-workflow-1746498186908
  labels:
    app.kubernetes.io/name: contoso-test-2
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: contoso-test-2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000